--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--


-- --------------------------------------------------------------------------------
-- Create Schemas
-- --------------------------------------------------------------------------------

IF NOT EXISTS ( 
	SELECT sys_sch.name 
	FROM sys.schemas sys_sch 
	WHERE sys_sch.name = N'dbo' )
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA [dbo] AUTHORIZATION dbo'
END
GO


-- --------------------------------------------------------------------------------
-- Create Tables
-- --------------------------------------------------------------------------------

CREATE TABLE [dbo].[syslogbuffer] ( 
	[slrec_id] BIGINT IDENTITY ( 1, 1 )  NOT NULL, 
	[slrec_timestamp] VARCHAR( 32 ) DEFAULT '('slrec_timestamp')' NULL, 
	[slrec_shortdateandtime] VARCHAR( 32 ) DEFAULT '('slrec_shortdateandtime')' NULL, 
	[slrec_tag] VARCHAR( 16 ) DEFAULT '('slrec_tag')' NULL, 
	[slrec_origin] VARCHAR( 16 ) DEFAULT '('slrec_origin')' NULL, 
	[slrec_severityid] BIGINT DEFAULT '('0')' NULL, 
	[slrec_severitydesc] VARCHAR( 32 ) DEFAULT '('severitydesc')' NULL, 
	[slrec_facilityid] BIGINT DEFAULT '('0')' NULL, 
	[slrec_facilitydesc] VARCHAR( 32 ) DEFAULT '('slrec_facilitydesc')' NULL, 
	[slrec_sourceip] VARCHAR( 20 ) DEFAULT '('slrec_sourceip')' NULL, 
	[slrec_sourcefqdn] VARCHAR( 32 ) DEFAULT '('slrec_sourcefqdn')' NULL, 
	[slrec_message] VARCHAR( 2048 ) DEFAULT '('slrec_message')' NULL )
GO

